<a href="https://colab.research.google.com/github/boing-86/Daily_Study/blob/main/0802pandas_torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
df_data = pd.read_csv(data_url, sep='\s+', header=None)
df_data.head()

0     1     2   3      4      5     6       7   8      9     10  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3  0.03237   0.0  2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4  0.06905   0.0  2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   

       11    12    13  
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2

In [4]:
df_data.columns = ['CRIM','ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO' ,'B', 'LSTAT', 'MEDV']

df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [5]:
print(df_data.values)
print(type(df_data.values))

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 3.9690e+02 4.9800e+00 2.4000e+01]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 3.9690e+02 9.1400e+00 2.1600e+01]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 3.9283e+02 4.0300e+00 3.4700e+01]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 5.6400e+00 2.3900e+01]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 3.9345e+02 6.4800e+00 2.2000e+01]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 7.8800e+00 1.1900e+01]]
<class 'numpy.ndarray'>


In [7]:
import pandas as pd
import numpy as np

In [10]:
list_data = [1,2,3,4,5]
example_obj = pd.Series(data=list_data)
example_obj

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [13]:
list_name = ["a", "b", "c", "d", "e"]
example_obj = pd.Series(data=list_data, index = list_name)
example_obj

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [16]:
print(example_obj.values)
type(example_obj.values)

[1 2 3 4 5]


numpy.ndarray

In [18]:
dict_data = {"a" : 1, "b":2, "c":3, "d":4, "e":5}
example_obj = pd.Series(dict_data, dtype=np.float32, name="example_data")
example_obj

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: example_data, dtype: float32

In [20]:
print(example_obj["a"])
example_obj["a"] = 3.2
print(example_obj)

1.0
a    3.2
b    2.0
c    3.0
d    4.0
e    5.0
Name: example_data, dtype: float32


In [21]:
example_obj[example_obj > 2]

a    3.2
c    3.0
d    4.0
e    5.0
Name: example_data, dtype: float32

In [22]:
example_obj * 2

a     6.4
b     4.0
c     6.0
d     8.0
e    10.0
Name: example_data, dtype: float32

In [23]:
np.exp(example_obj)

a     24.532530
b      7.389056
c     20.085537
d     54.598148
e    148.413162
Name: example_data, dtype: float32

In [25]:
"b" in example_obj

True

In [27]:
example_obj.to_dict()

{'a': 3.200000047683716, 'b': 2.0, 'c': 3.0, 'd': 4.0, 'e': 5.0}

In [28]:
example_obj.values

array([3.2, 2. , 3. , 4. , 5. ], dtype=float32)

In [29]:
example_obj.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [30]:
example_obj.name = "numbers"
example_obj.index.name = "alphabet"
example_obj

alphabet
a    3.2
b    2.0
c    3.0
d    4.0
e    5.0
Name: numbers, dtype: float32

In [32]:
dict_data_1 = {"a" : 1, "b":2, "c":3, "d":4, "e":5}
indexes = ["a", "b", "c", "d", "e", "f", "g", "h"]
series_obj_1 = pd.Series(dict_data_1, index = indexes)
series_obj_1

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    NaN
g    NaN
h    NaN
dtype: float64

### Data Frame

In [33]:
import pandas as pd
import numpy as np

In [34]:
raw_data = {"first_name" : ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'],
            "last_name":['Miller', 'Jacobson', 'Ali', 'Jilner', 'Coze'],
            "age" : [42, 32, 36, 25, 86],
            "city" : ['Seoul', 'Chicago', 'Newyork', 'Shanghai', 'Miami']}
df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'city'])
df

first_name last_name  age      city
0      Jason    Miller   42     Seoul
1      Molly  Jacobson   32   Chicago
2       Tina       Ali   36   Newyork
3       Jake    Jilner   25  Shanghai
4        Amy      Coze   86     Miami

In [35]:
pd.DataFrame(raw_data, columns = ['age', 'city'])

age      city
0   42     Seoul
1   32   Chicago
2   36   Newyork
3   25  Shanghai
4   86     Miami

In [37]:
df = pd.DataFrame(raw_data, columns = ['first_name','last_name', 'age', 'city', 'debt'])
df.first_name

0    Jason
1    Molly
2     Tina
3     Jake
4      Amy
Name: first_name, dtype: object

In [38]:
df["first_name"]

0    Jason
1    Molly
2     Tina
3     Jake
4      Amy
Name: first_name, dtype: object

In [39]:
df.loc[1]

first_name       Molly
last_name     Jacobson
age                 32
city           Chicago
debt               NaN
Name: 1, dtype: object

In [42]:
df["age"].iloc[2:]

2    36
3    25
4    86
Name: age, dtype: int64

In [43]:
s = pd.Series(np.nan, index = [49,48,47,46,45, 1, 2, 3, 4, 5])
s

49   NaN
48   NaN
47   NaN
46   NaN
45   NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
dtype: float64

In [44]:
s.iloc[:3]

49   NaN
48   NaN
47   NaN
dtype: float64

In [45]:
df.age > 40

0     True
1    False
2    False
3    False
4     True
Name: age, dtype: bool

In [46]:
df.debt = df.age > 40
df

first_name last_name  age      city   debt
0      Jason    Miller   42     Seoul   True
1      Molly  Jacobson   32   Chicago  False
2       Tina       Ali   36   Newyork  False
3       Jake    Jilner   25  Shanghai  False
4        Amy      Coze   86     Miami   True

In [47]:
values = pd.Series(data = ["M", "F", "F"], index = [0, 1, 3])
values

0    M
1    F
3    F
dtype: object

In [48]:
df["sex"] = values
df

first_name last_name  age      city   debt  sex
0      Jason    Miller   42     Seoul   True    M
1      Molly  Jacobson   32   Chicago  False    F
2       Tina       Ali   36   Newyork  False  NaN
3       Jake    Jilner   25  Shanghai  False    F
4        Amy      Coze   86     Miami   True  NaN

In [49]:
df.T

0         1        2         3      4
first_name   Jason     Molly     Tina      Jake    Amy
last_name   Miller  Jacobson      Ali    Jilner   Coze
age             42        32       36        25     86
city         Seoul   Chicago  Newyork  Shanghai  Miami
debt          True     False    False     False   True
sex              M         F      NaN         F    NaN

In [50]:
df.values

array([['Jason', 'Miller', 42, 'Seoul', True, 'M'],
       ['Molly', 'Jacobson', 32, 'Chicago', False, 'F'],
       ['Tina', 'Ali', 36, 'Newyork', False, nan],
       ['Jake', 'Jilner', 25, 'Shanghai', False, 'F'],
       ['Amy', 'Coze', 86, 'Miami', True, nan]], dtype=object)

In [51]:
df.to_csv()

',first_name,last_name,age,city,debt,sex\n0,Jason,Miller,42,Seoul,True,M\n1,Molly,Jacobson,32,Chicago,False,F\n2,Tina,Ali,36,Newyork,False,\n3,Jake,Jilner,25,Shanghai,False,F\n4,Amy,Coze,86,Miami,True,\n'

In [52]:
df

first_name last_name  age      city   debt  sex
0      Jason    Miller   42     Seoul   True    M
1      Molly  Jacobson   32   Chicago  False    F
2       Tina       Ali   36   Newyork  False  NaN
3       Jake    Jilner   25  Shanghai  False    F
4        Amy      Coze   86     Miami   True  NaN

In [53]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

pd.DataFrame(pop)

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

### PyTorch Tensor  

In [65]:
import torch 

In [68]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [70]:
import torch
#https://school.programmers.co.kr/learn/courses/30/lessons/12950
#생각나서 실행해봤는데 잘 됨. 근데 프로그래머스에서는 import torch가 안됨.

a1 = torch.IntTensor([[1,2],[2,3]])
a2 = torch.IntTensor([[3,4],[5,6]])

print(a1+a2)

tensor([[4, 6],
        [7, 9]], dtype=torch.int32)
