<a href="https://colab.research.google.com/github/boing-86/Daily_Study/blob/main/vector_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
test_array = np.array([1,2,3,"4"], np.float32)
print(test_array)
test_array.dtype

[1. 2. 3. 4.]


dtype('float32')

In [7]:
test_array.shape

(4,)

In [9]:
tensor  = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]

In [16]:
np.array(tensor, float).ndim #ndim - 몇차원인지 출력

3

In [18]:
a_array = np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.int8)

In [21]:
np.array(a_array).nbytes

6

In [24]:
test_matrix = [[1,2,3,4],
                [5,6,7,8]]
np.array(test_matrix).shape

(2, 4)

In [33]:
np.array(test_matrix).reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

### Indexing, Slicing


In [50]:
test_array = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]], int)

In [49]:
test_array[:3,:] 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
test_array[:,1:3] #전체에 대하여 1,2열만 출력

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [82]:
test_array[:,::2] #전체에 대하여 0에서부터 +2열씩 출력 -> 0, 2열 출력

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

In [80]:
test_array[:2] #0, 1 행만 출력

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [85]:
test_array[::3] #0행부터 +3행씩 출력 -> 0, 3행

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [93]:
a = np.arange(100).reshape(10, 10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [96]:
a[:, -1]  #전체에 대하여 0에서부터 -1번째 열 -> 맨뒷열

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [99]:
a[::2, ::2] #십의 자리, 일의 자리가 모두 짝수인 숫자만 추출

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48],
       [60, 62, 64, 66, 68],
       [80, 82, 84, 86, 88]])

In [110]:
a[3::3, 3::3] #369에서 박수 두번쳐야하는 숫자들

array([[33, 36, 39],
       [63, 66, 69],
       [93, 96, 99]])

In [111]:
a[3::3, 3::3].reshape(1, -1)

array([[33, 36, 39, 63, 66, 69, 93, 96, 99]])

### Creation Functions

In [115]:
np.arange(100).reshape(20, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [118]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [122]:
np.zeros(shape=(5, 2), dtype = np.int8)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int8)

In [127]:
np.identity(n=5, dtype=np.int8) #단위행렬

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [132]:
np.eye(N=3, M= 5, k=2, dtype=np.int8) #대각선이 1인 행렬. K값부터 시작

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [136]:
test_matrix = np.arange(100).reshape(10, 10)
np.diag(test_matrix, k=0) #대각선 시작을 k로 지정 가능

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [154]:
test_array = np.random.uniform(0, 1, 10).reshape(1,10) #균등분포
print(test_array)
test_array = np.random.normal(0, 1, 10).reshape(1,10) #정규분포
print(test_array)

[[0.82555568 0.51972131 0.03422078 0.08260537 0.76572107 0.82019199
  0.33962067 0.12123221 0.40908907 0.39891837]]
[[ 0.24846464 -1.30504568  1.84290173 -0.88064465 -0.03031596 -1.3285691
  -0.6336746   0.78322676  0.5605041  -0.67637057]]


### n-d-array operation functions

In [158]:
test_array = np.arange(1, 11)
test_array.sum(dtype=np.float32)

55.0

In [166]:
test_array = np.arange(100).reshape(10, 10)
print(test_array)
print(test_array.sum(axis = 0))
print(test_array.sum(axis = 1))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[450 460 470 480 490 500 510 520 530 540]
[ 45 145 245 345 445 545 645 745 845 945]


In [173]:
test_array = np.arange(1,28).reshape(3, 3, 3)
test_array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [175]:
print(test_array.sum(axis = 0))
print(test_array.sum(axis = 1))
print(test_array.sum(axis = 2))

[[30 33 36]
 [39 42 45]
 [48 51 54]]
[[12 15 18]
 [39 42 45]
 [66 69 72]]
[[ 6 15 24]
 [33 42 51]
 [60 69 78]]


In [177]:
test_array = np.arange(1, 13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [179]:
test_array.std()
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [185]:
a = np.arange(1, 4).reshape(3)
b = np.arange(4, 7).reshape(3)
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [187]:
a = np.arange(1, 4).reshape(3, 1)
b = np.arange(4, 7).reshape(3, 1)
np.hstack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [188]:
a = np.arange(1, 4).reshape(1, 3)
b = np.arange(4, 7).reshape(1, 3)
np.concatenate((a, b), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [191]:
a = np.arange(1, 5).reshape(2, 2)
b = np.arange(5, 7).reshape(2, 1)
print(a)
print(b)
np.concatenate((a, b), axis=1)

[[1 2]
 [3 4]]
[[5]
 [6]]


array([[1, 2, 5],
       [3, 4, 6]])

In [195]:
np.concatenate((a, b), axis=1).tolist()

[[1, 2, 5], [3, 4, 6]]

### Array 간의 operations

scalar 연산도 가능. 각 값에 대하여 각각 scalar 연산을 함. 

In [201]:
test1_array = np.arange(1, 7).reshape(2,3)
test2_array = np.arange(7, 13).reshape(2,3)
print(test1_array)
print(test2_array)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [202]:
test1_array + test2_array

array([[ 8, 10, 12],
       [14, 16, 18]])

In [203]:
test2_array - test1_array

array([[6, 6, 6],
       [6, 6, 6]])

In [208]:
test2_array * test1_array  #같은 위치의 값을 곱해줌. 행렬의 곱은 @

array([[ 7, 16, 27],
       [40, 55, 72]])

In [212]:
test_a = np.arange(1, 7).reshape(2, 3)
test_b = np.arange(7, 13).reshape(3, 2)
print(test_a @ test_b)
print(test_a.dot(test_b))

[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]


In [215]:
print(test_a.transpose())
print(test_a.T)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


### numpy performance - time
concatenate 는 list가 더 빠름

In [217]:
def sclar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result 

iternation_max = 100

vector = list(range(iternation_max))
scalar = 2

%timeit sclar_vector_product(scalar, vector) # for loop을 이용한 성능

The slowest run took 4.66 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 9.39 µs per loop


In [219]:
%timeit [scalar * value for value in range(iternation_max)] # list comprehension을 이용한 성능
%timeit np.arange(iternation_max) * scalar # numpy를 이용한 성능

100000 loops, best of 5: 6.94 µs per loop
The slowest run took 43.43 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 2.03 µs per loop


### Numpy Comparison

In [220]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [222]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [226]:
np.any(a>5), np.any(a<0), np.all(a>5), np.all(a>=0)

(True, False, False, True)

In [228]:
test_a = np.arange(1, 7)
test_b = np.arange(7, 13)
test_a > test_b, test_a < test_b

(array([False, False, False, False, False, False]),
 array([ True,  True,  True,  True,  True,  True]))

In [229]:
test_a == test_b

array([False, False, False, False, False, False])

In [232]:
(test_a > test_b).any()

False

In [234]:
b = np.array([True, False, True], bool)
c = np.array([False, True, False], bool)
print(np.logical_or(b, c))
print(np.logical_and(b, c))

[ True  True  True]
[False False False]


In [236]:
a = np.arange(5, 15)
np.where(a>10) #조건에 만족하는 index를 알려줌

(array([6, 7, 8, 9]),)

In [240]:
test_a = np.array([1,3,0])
np.where(test_a > 0, 3, 2) 
# 각 값에 대하여 조건을 수행하고 True면 3을 반환, False면 2를 반환

array([3, 3, 2])

In [243]:
test_a = np.array([1, np.NaN, np.Inf])
print(np.isnan(test_a))
print(np.isfinite(test_a))

[False  True False]
[ True False False]


In [247]:
a = np.array([1,2,4,8,24,84,80,29, 66])
np.argmax(a), np.argmin(a) #인덱스 반환

(5, 0)

In [252]:
a = np.array([1,2,4,8,24,84,80,29, 66]).reshape(3,3)
a

array([[ 1,  2,  4],
       [ 8, 24, 84],
       [80, 29, 66]])

In [255]:
np.argmax(a, axis=0), np.argmax(a, axis=1)

(array([2, 2, 1]), array([2, 2, 0]))

### Boolean / Fancy Index

In [258]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7])
print(test_array > 3) 
test_array[test_array > 3] # 조건에 맞는 값 출력

[False  True False False False  True  True  True]


array([4, 8, 9, 7])

In [265]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b, c] #(0,0),(0,1),(1,1),(1,1),(0,1)


array([ 1.,  4., 16., 16.,  4.])

### numpy data io

In [267]:
text = np.loadtxt("") #text

array([[1., 1., 4., 4., 1.],
       [1., 4., 4., 4., 4.]])